# ndarray的特性
## 1. 多维性

In [2]:
import numpy as np

arr = np.array(5)   # 0维
print(arr)
print('arr的纬度:', arr.ndim)

arr1 = np.array([1,2,3,4])
print(arr1)
print('arr1的纬度：',arr1.ndim)

arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)
print('arr2的纬度：', arr2.ndim)

5
arr的纬度: 0
[1 2 3 4]
arr1的纬度： 1
[[1 2 3]
 [4 5 6]]
arr2的纬度： 2


## 2. 同质性  
**不同数据类型会被强制转换为相同数据类型** 


In [3]:
arr = np.array([1,'hello'])     #不同数据类型会被强制转化成相同数据类型
print(arr)

arr1 = np.array([1,2.5])
print(arr1)

['1' 'hello']
[1.  2.5]


# ndarray的属性

In [4]:
arr = np.array(1)
print(arr)
print('arr的形状：',arr.shape)    

arr1  = np.array([1,2,3])
print(arr1)
print('arr1的形状',arr1.shape)
print('arr1的维度：',arr1.ndim)
print('arr1元素的个数：',arr1.size)

arr2 = np.array([[1,2.5,3],[4,5,6]])
print(arr2)
print('arr2的形状：',arr2.shape)
print('arr2的维度：',arr2.ndim)
print('arr2元素的个数：',arr2.size)
print('arr2元素数据的类型:',arr2.dtype)
print('元素的转置:\n',arr2.T)

1
arr的形状： ()
[1 2 3]
arr1的形状 (3,)
arr1的维度： 1
arr1元素的个数： 3
[[1.  2.5 3. ]
 [4.  5.  6. ]]
arr2的形状： (2, 3)
arr2的维度： 2
arr2元素的个数： 6
arr2元素数据的类型: float64
元素的转置:
 [[1.  4. ]
 [2.5 5. ]
 [3.  6. ]]


# ndarray的创建

In [5]:
#基础创建方法
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
list = [0,1,2,3]
arr1 = np.array(list,dtype= np.float64)
print(arr1)

[[1 2 3]
 [4 5 6]]
[0. 1. 2. 3.]


In [6]:
#copy
arr2 = np.copy(arr1)
print(arr2)

[0. 1. 2. 3.]


In [10]:
#预定义形状
#全0 全1 未初始化 固定值
#全0
tup = (2,4)
arr = np.zeros(tup,dtype= int)
print(arr)

#全1
arr = np.ones((3,4))
print(arr)

#未初始化
arr = np.empty((3,4),dtype= np.float64)
print(arr)

arr = np.full((3,4), 25)
print(arr)
arr1 = np.empty_like(arr)
print(arr1)
arr1 = np.ones_like(arr)
print(arr1)
arr1 = np.zeros_like(arr)
print(arr1)
arr1 = np.full_like(arr,10)
print(arr1)


[[0 0 0 0]
 [0 0 0 0]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[25 25 25 25]
 [25 25 25 25]
 [25 25 25 25]]
[[4607182418800017408 4607182418800017408 4607182418800017408
  4607182418800017408]
 [4607182418800017408 4607182418800017408 4607182418800017408
  4607182418800017408]
 [4607182418800017408 4607182418800017408 4607182418800017408
  4607182418800017408]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


In [13]:
#等差数列
arr = np.arange(0,10,2) #start end step
print(arr)

#等间隔数列
arr = np.linspace(0,10,4) #start end 份数
print(arr)

#对数间隔数列
arr = np.logspace(0,10,2,base=2)    #base表示底数
print(arr)

[0 2 4 6 8]
[ 0.          3.33333333  6.66666667 10.        ]
[1.000e+00 1.024e+03]


In [35]:
#特殊矩阵
#单位矩阵：主对角线上的数字为1，其他的数字为0
arr = np.eye(3,4)     #几行几列
print(arr)

#对角矩阵：主对角线上非0，其他为0
arr = np.diag([5,2,2,4])
print(arr)

#随机数组生成
#生成0到1之间的随机浮点数（均匀分布）
arr = np.random.rand(2,3)
print(arr)
#生成指定范围区间的随机浮点数
arr = np.random.uniform(3,6,(2,3))  #uniform 起始数 终止数 （行，列）
print(arr)
#生成指定范围区间的随机整数
arr = np.random.randint(3,6,(2,3))  #uniform 起始数 终止数 （行，列）
print(arr)

#生成随机数列（正态分布） （-3到3之间）
#两边小，中间大
arr = np.random.randn(2,3)
print(arr)

#设置随机种子
np.random.seed(15)
are = np.random.randn(2,3)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
[[5 0 0 0]
 [0 2 0 0]
 [0 0 2 0]
 [0 0 0 4]]
[[0.30591892 0.30447436 0.11174128]
 [0.24989901 0.9176299  0.26414685]]
[[5.15332106 5.5971451  5.42123845]
 [3.63165175 3.50172909 3.14011918]]
[[4 4 3]
 [4 5 5]]
[[-0.36852691 -0.21511962 -0.12742666]
 [-1.55106048 -1.23004904 -1.45905095]]


# ndarray的数据类型  
布尔类型 bool  
整数类型 int  uint  
浮点数 float  
复数 complex  

In [50]:
arr  = np.array([1,2,4,0], dtype= np.bool)
print(arr)
arr  = np.array([1,-29990,4,0], dtype= np.int16)
print(arr)


[ True  True  True False]
[     1 -29990      4      0]


# 索引与切片

In [67]:
# 一维数组的索引与切片
arr = np.random.randint(1,100,20)
print(arr)
print(arr[0])
print(arr[0:10:2]) #start : end 左包右不包
print(arr[slice(0,11,2)])
print(arr[(arr>10) & (arr<70)])  #bool索引  & ---> 与

#二维数组的索引与切片
arr = np.random.randint(1,100,(3,4))
print(arr)
print(arr[1,2])
print(arr[0:2,1:3])
print(arr[1,:][arr[1,:]>50])


[98 40 46 74 47 96 58 62 37  4 98 57  5 55 35 88 36 77 43  3]
98
[98 46 47 58 37]
[98 46 47 58 37 98]
[40 46 47 58 62 37 57 55 35 36 43]
[[11 38 40 73]
 [17 92 32 65]
 [57 43 43 36]]
32
[[38 40]
 [92 32]]
[92 65]


# ndarray的运算

In [ ]:
#算数运算
#数组与数组的运算
a = np.array([[1,2,5],[2,54,6],[2,4,5]])
b = np.array([[2,4,-5],[2,4,1],[9,6,7]])
print(a + b)
print(a - b)
print(a * b)
print(a / b)

#数组与标量的运算
print(a + 3)    #让每个元素加3
print(a *3)

#矩阵的运算
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[2,2,2],[1,1,1],[3,3,3]])
print(a @ b)    #矩阵乘法


[[ 3  6  0]
 [ 4 58  7]
 [11 10 12]]
[[-1 -2 10]
 [ 0 50  5]
 [-7 -2 -2]]
[[  2   8 -25]
 [  4 216   6]
 [ 18  24  35]]
[[ 0.5         0.5        -1.        ]
 [ 1.         13.5         6.        ]
 [ 0.22222222  0.66666667  0.71428571]]
[[ 4  5  8]
 [ 5 57  9]
 [ 5  7  8]]
[[  3   6  15]
 [  6 162  18]
 [  6  12  15]]


# Numpy的常用函数  
## 1. 基本数学函数

In [87]:
#计算平方根
print(np.sqrt(9))
print(np.sqrt([1,4,9]))
arr = np.array([1,25,81])
print(np.sqrt(arr))

#计算指数
print(np.exp(1))
print(np.exp(3))

#计算自然对数
print(np.log(2.71))
print(np.log(np.e))

#计算正弦值 和 余弦值
print(np.sin(np.pi/6))
print(np.cos(np.pi))

#计算绝对值
arr = [1,-10,2,3]
print(arr)
print(np.abs(arr))

#计算a的b次幂
print(np.power(arr,2))  # a,b 

#四舍五入
print(np.round([3.2 ,4.5 ,5.6,7.1]))

#向上取整，向下取整
arr = np.array([1.1, 2.3, 4.7, 7.8])
print(arr)
print(np.ceil(arr))     #向上取整
print(np.floor(arr))    #向下取整

#检测缺失值NaN
np.isnan([1,2,np.nan,3])

3.0
[1. 2. 3.]
[1. 5. 9.]
2.718281828459045
20.085536923187668
0.9969486348916096
1.0
0.49999999999999994
-1.0
[1, -10, 2, 3]
[ 1 10  2  3]
[  1 100   4   9]
[3. 4. 6. 7.]
[1.1 2.3 4.7 7.8]
[2. 3. 5. 8.]
[1. 2. 4. 7.]


array([False, False,  True, False])

## 2. 统计函数

In [104]:
arr = np.random.randint(1,20,7)
print(arr)

#求和
print(np.sum(arr))
print(np.sum([1,2,3]))

#计算平均值
print(np.mean(arr))

#计算中位数
print(np.median(arr))
print(np.median([1,2,3,4]))

#计算标准差、方差
print(np.var([1,2,3]))
print(np.std([1,2,3]))

#计算最大值、最小值
print(arr)
print(np.max(arr), np.argmax(arr))
print(np.min(arr),np.argmin(arr))

#分位数 注意：与中位数区分
arr = [44,47,64,67]
#---------------------
#44     47     64   67
#中位数： (47+64)/2
print(np.median(arr))
print(np.percentile(arr,20))    #取百分之多少
#分位数：3*0.2 = 0.6    (有三个间隔)
#44 + （47-44）*0.6

#累计和、累计积
arr = np.array([1,2,3])
print(np.sum(arr))
print(np.cumsum(arr))
print(np.cumprod(arr))


[ 7 14 12  6  8 10 19]
76
6
10.857142857142858
10.0
2.5
0.6666666666666666
0.816496580927726
[ 7 14 12  6  8 10 19]
19 6
6 3
55.5
45.8
6
[1 3 6]
[1 2 6]


## 3. 比较函数

In [126]:
#是否大于
print(np.greater([1,2,3,4,5,6],3))

#是否小于
print(np.less([1,2,3,4,5,6],3))

#是否等于
print(np.equal([1,2,3,4,5,6],3))
print(np.equal([1,2,3],[3,2,3]))

#逻辑与
print(np.logical_and([1,0],[2,1]))
#逻辑非
print(np.logical_not([1,2,0]))
#逻辑或
print(np.logical_or([1,0,0],[2,1,0]))

#检测元素是否至少有一个是True
print(np.any([0,0,0]))
#检测元素是否全是True
print(np.all([1,1,0]))

#自定义条件
#np.where(条件,符合条件 ,不符合条件 )
arr = np.array([1,2,3,4,5,6])
print(np.where(arr>=3,arr,0))

score = np.random.randint(0,100,10)
print(score)
print(np.where(
    score < 60, '不及格',np.where(
        score < 80, '良好', '优秀'
    )
))
#np.select(条件，返回的结果)
print(np.select([score > 80,(score>=60) & (score<=80),score < 60],
                ['优秀','良好','及格'],
                default= '未知'))

[False False False  True  True  True]
[ True  True False False False False]
[False False  True False False False]
[False  True  True]
[ True False]
[False False  True]
[ True  True False]
False
False
[0 0 3 4 5 6]
[ 7 93 98 80 97 25 71 55 81 35]
['不及格' '优秀' '优秀' '优秀' '优秀' '不及格' '良好' '不及格' '优秀' '不及格']
['及格' '优秀' '优秀' '良好' '优秀' '及格' '良好' '及格' '优秀' '及格']


## 4. 排序函数

In [139]:
np.random.seed(20)
#.sort()
arr = np.random.randint(1,100,10)
print(arr)
#arr.sort()  #改变了arr
print(arr)
print(np.sort(arr)) #不改变arr
print(np.argsort(arr))
print(arr)
print("-------")
#去重函数
print(np.unique(arr))
print(arr)

#数组的拼接
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(np.concatenate((arr1,arr2)))

#数组的分割
print(np.split(arr,5))
print(np.split(arr,[3,6,9]))

#调整数组的形状
print(np.reshape(arr,[2,5]))

[91 16 96 29 91 10 21 76 23 72]
[91 16 96 29 91 10 21 76 23 72]
[10 16 21 23 29 72 76 91 91 96]
[5 1 6 8 3 9 7 0 4 2]
[91 16 96 29 91 10 21 76 23 72]
-------
[10 16 21 23 29 72 76 91 96]
[91 16 96 29 91 10 21 76 23 72]
[1 2 3 4 5 6]
[array([91, 16], dtype=int32), array([96, 29], dtype=int32), array([91, 10], dtype=int32), array([21, 76], dtype=int32), array([23, 72], dtype=int32)]
[array([91, 16, 96], dtype=int32), array([29, 91, 10], dtype=int32), array([21, 76, 23], dtype=int32), array([72], dtype=int32)]
[[91 16 96 29 91]
 [10 21 76 23 72]]
